name: faiadashu
description: Faiadashu FHIRDash - Build beautiful healthcare apps fast — use the Flutter™ SDK and follow the HL7® FHIR® standard.

version: 0.11.9
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  collection: ^1.17.0
  fhir: ^0.12.0
  fhir_path: ^0.12.0
  #  fhir:
  #    path: /Users/tilo/Projects/fhir/fhir
  #  fhir_path:
  #    path: /Users/tilo/Projects/fhir/fhir_path
  file_selector: ^1.0.3
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.2.0
  markdown: ^7.2.2
  mime: ^1.0.4
  scrollable_positioned_list: ^0.3.8
  simple_html_css: ^5.0.0
  webview_flutter: ^4.9.0
  webview_flutter_web: ^0.2.3+2

dependency_overrides:
  intl: ^0.19.0

  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
